wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: TabPFN
dataset:
  desc: null
  value: meta-dataset
epochs:
  desc: null
  value: 50
query_batch_size:
  desc: null
  value: 16
support_batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687796606.867159
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
